name: Bright Storybook
on: [push]
jobs:
  tests:
    runs-on: ubuntu-18.04
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v2.3.3

      - name: Setup Node 12.6.1
        uses: actions/setup-node@v1.4.3
        with:
          node-version: 12.16.1
          always-auth: true
          scope: '@smartpension'
          registry-url: 'https://npm.pkg.github.com'

      - name: Set npm config
        run: npm config set //npm.pkg.github.com/:_authToken ${NPM_TOKEN}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependancies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run jest tests
        run: yarn test

      - name: Build package
        run: yarn build --if-present
